name: i2i
channels:
  - pytorch
  - conda-forge
dependencies:
  - pytorch<=1.12.1
  - torchvision
  - numpy
  - pandas
  - tqdm
  - tensorboardX>=1.14
  - scipy 
  - pip:
    - opencv-python
    - clean-fid
